version: "2.2"
networks:
  flink:
    name: flink
    driver: bridge
   
services:
  jobmanager:
    image: flink:latest
    networks:
      - flink
      
    ports:
      - "8081:8081"
     
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    extra_hosts:
      - "host.docker.internal:host-gateway"

  taskmanager:
    networks:
      - flink
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    extra_hosts:
      - "host.docker.internal:host-gateway"

    
