#Generi suonati da altri musicisti nella stessa citta'
PREFIX musico: <http://purl.org/ontology/musico#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?genre
WHERE{
  # ?user sostituibile con [ mo:uuid 1234 ]
  ?user foaf:based_near ?city.	
  ?others foaf:based_near ?city;
          musico:in_participation/
          musico:played_musical_work/
          mo:genre ?genre .
  FILTER(?user != ?others)
}