# Musicisti nelle vicinanze dell'utente
# che suonano generi simili al suo
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX musico: <http://purl.org/ontology/musico#> 
SELECT DISTINCT ?others ?user
WHERE {
  # ?User mo:uuid "1" .
  ?user foaf:based_near ?location ;
        musico:plays_genre ?genre .
  ?others foaf:based_near ?location ;
          musico:plays_genre ?genre .  
          # musico:plays_genre [ mo:similar_to ?genre ] .
  FILTER (?user != ?others)
}