# Luoghi vicini all'utente dove puo' suonare
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema:<https://schema.org/docs/schemaorg.owl> 
SELECT DISTINCT ?place
WHERE {
    #?user mo:uuid 123 .
    #[mo:uuid 123] foaf:based_near ?location .
    ?user foaf:based_near ?location .
    ?place schema:location ?location .
    # ?place ha disponibilita'?
    # ?place ha strumenti?
    # ?place e' aperto?
}